### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by leranp** [slydiman/ha_custom_onvif#1]
Thanks you for this custom addon, my camera had the some problem with the original onvif component in HA that the sensor didn't worked at all, and with your component i was able to see all of the camera sensor and it works fine.
But after a while i saw that the memory was eating by this component, do you want me to send logs?
![Screenshot_20210408-205232_Home Assistant.jpg](https://user-images.githubusercontent.com/9452319/114074453-0d9ba380-98ad-11eb-892a-8a4f1b07133e.jpg)

**Comment by slydiman** [comment]
Re: [slydiman/ha_custom_onvif] Memory problem (#1)



Hello leranp

Actually I'm not HA expert.I have a lot experience with cameras, video streaming, video processing (here is my project https://restore.media )I used Wireshark to dump tcp traffic between HA and cameras to investigate issues.
Finally I was able to fix some issues.
But currently I have no enough experience to debug any memory leaks in HA components.
The problem may be in the sensor or binary_sensor implementation, not even in onvif component.
Try to open the issue in https://github.com/home-assistant/core
A memory leak is very dangerous, so probably it will be fixed quickly.

Thanks,
Dmitry

Thursday, April 8, 2021 9:58:03 PM You wrote:





Thanks you for this custom addon, my camera had the some problem with the original onvif component in HA that the sensor didn't worked at all, and with your component i was able to see all of the camera sensor and it works fine.
But after a while i saw that the memory was eating be thia component, do you want me to send logs?
