### ISSUE TITLE
Homeassistant 2021.6

### ISSUE THREAD

**Issue by gomble** [slydiman/ha_custom_onvif#2]
Hello since homeassistant 2021.6 i have the problem again:

zeep.exceptions.XMLParseError: No namespace defined for 'wsrf-rw' ('wsrf-rw:ResourceUnknownFault')

**Comment by slydiman** [comment]
I have added a version to manifest.json to make HA 2021.6+ happy.
Just download the [latest release](https://github.com/slydiman/ha_custom_onvif/releases/tag/2021-06-05)
